name    'ekohl-nrpe_basic'
version '0.0.6'
source 'git://github.com/ekohl/nrpe_basic.git'
author 'ekohl'
license 'Apache License Version 2.0'
summary 'Manage basic NRPE local checks and the service'
description 'Manage basic NRPE local checks and the service'
project_page 'https://github.com/ekohl/nrpe_basic'
